[package]
name = "求极差"
version = "0.1.0"
authors = ["Kong-Jun <kongjun18@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
